### ISSUE TITLE
Construct persistent Markov Chain

### ISSUE THREAD

**Issue by Kublai-Jing** [aripakman/hmc-binary#1]
Hi,
I am interested in learning RBM using persistent MCMC with your HMC sampler.
My question is, how do we construct several parallel persistent markov chains with the code? Do we just store the samples returned by HMC and use them as the initial_X in the next round?

Thank you.

**Comment by aripakman** [comment]
Hi Kublai-Jing,

thanks for your interest in the HMC sampler. As you suggest, storing the samples and using them as the initial condition in the next round will work. 

But I think that, for the specific case of RBM, the HMC sampler will not do better than the standard block Gibbs sampler. The reason is that when conditioning on one layer of the RBM, the variables on the other layer are independent, and therefore the Gibbs sampler mixes very fast. 

Ari

**Comment by Kublai-Jing** [comment]
Hi Ari,
Thank you for the reply !
my model is not really a RBM, but more like a semi-RBM so I thought it's worth trying to run HMC instead of block Gibbs.
Another quick question: do I have to store the 'velocity' variables and use them to initialize the V in the next round ? or it is okay with your code to just resample from a standard Gaussian everytime I continue the Markov Chain.

Thank you.

**Comment by aripakman** [comment]
Hi Kublai-Jing,
the velocity should be resampled for every new sample in the Markov chain.
Ari

**Comment by Kublai-Jing** [comment]
Thanks a lot !
